In [93]:
import numpy as np

In [94]:
def sigmoid(x):
    return (1. / (1+np.exp(-x)))

In [95]:
def sigmoidDeriv(x):
    return sigmoid(x) * (1-sigmoid(x))

In [96]:
print sigmoidDeriv(0)
print sigmoidDeriv(1)
print sigmoidDeriv(-1)

0.25
0.196611933241
0.196611933241


In [97]:
data = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
output_arr = np.array([[0],[1],[1],[0]])

# initialize random set of weights (3 -> 1)
np.random.seed(1)
w_1 = np.random.random((3,1))*2 - 1
print w_1
print data

for i in range(10000):
    l0 = data
    y = output_arr

    l1 = l0.dot(w_1)
    l1_output = sigmoid(l1)
    l1_error = y - l1_output
    l1_delta = l1_error * sigmoidDeriv(l1)

    w_1 += l0.T.dot(l1_delta)

print "Output after training: "
print l1_output

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Output after training: 
[[ 0.00966449]
 [ 0.99211957]
 [ 0.99358898]
 [ 0.00786506]]
